os: osx
osx_image: xcode8.2
xcode_workspace: "Placeholder"
xcode_sheme: "Placeholder"
before_install:
  - brew update && brew tap caskroom/cask && brew cleanup && brew cask cleanup
  - brew install homebrew/dupes/apple-gcc42
  - brew install -f ode
  - brew install -f wxmac
  - brew install -f freetype
  - brew install -f python apple-gcc42 libav gtk+ jpeg libpng ode --enable-double-precision libtiff 
  - brew install mongodb yaml-cpp
  - brew install soci
  - brew install eigen
  - pip install bcrypt pymongo requests pycrypto semidbm pyyaml
  - sudo installer -pkg travis/Panda3D.mpkg -target /
  - 

script:
  - cd tools
  - python prepare_client.py --resources-dir=../resources -i cleanse.py -x rpc-invasions.py --vfs ../PPYTHON_PATH #this will be your own prepare client
  - python build_client.py --build-dir build/toontown/toonbase --main-module ClientStart.py # this will be your build command. should be same cross-platofrm